server:
  port: 8081

spring:
  config:
    import: optional:file:../config/application-local.yml
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.promptcraft: DEBUG
